/**
 * Loyverse REST API 응답 zod 스키마 — 외부 입력은 경계에서 파싱한다(CLAUDE.md 컨벤션).
 * 실제 API 응답에는 여기 정의하지 않은 필드가 더 있을 수 있으므로 `.passthrough()`로
 * 알 수 없는 필드를 허용하고, 우리가 실제로 쓰는 필드만 엄격히 검증한다.
 * FixtureLoyverseClient(mocks)와 T3 실어댑터(adapters/loyverseClient)가 공유한다.
 */
import { z } from "zod";

export const LvStoreSchema = z
  .object({
    id: z.string(),
    name: z.string(),
  })
  .passthrough();

export const LvItemVariantSchema = z
  .object({
    variant_id: z.string(),
    sku: z.string().nullable(),
  })
  .passthrough();

export const LvItemSchema = z
  .object({
    id: z.string(),
    item_name: z.string(),
    category_id: z.string().nullable(),
    variants: z.array(LvItemVariantSchema).min(1),
  })
  .passthrough();

export const LvReceiptLineItemSchema = z
  .object({
    variant_id: z.string(),
    item_id: z.string(),
    quantity: z.number(),
    gross_total_money: z.number(),
    total_discount: z.number(),
  })
  .passthrough();

export const LvReceiptSchema = z
  .object({
    receipt_number: z.string(),
    store_id: z.string(),
    // "SALE" | "REFUND" — 실제 API 값. 이 필드가 있어야 환불을 구분할 수 있다(부호는 ETL에서 반전).
    receipt_type: z.enum(["SALE", "REFUND"]),
    // 환불 영수증에서만 원 판매 영수증 번호를 담는다. 공식 문서: "Only for refund receipts".
    refund_for: z.string().nullable(),
    // 자동 생성 시각. 공식 문서: "The autogenerated date and time when the receipt was created".
    created_at: z.iso.datetime(),
    // 공식 문서: "The date and time when the receipt was updated." — 증분 동기화 watermark의 기준.
    updated_at: z.iso.datetime(),
    // 기본값은 created_at과 같지만, 과거 시각으로 backdate될 수 있다(이관 데이터 등).
    receipt_date: z.iso.datetime(),
    // 취소된 영수증의 취소 시각. 취소되지 않았으면 null.
    cancelled_at: z.iso.datetime().nullable(),
    line_items: z.array(LvReceiptLineItemSchema),
  })
  .passthrough();

export const LvInventoryLevelSchema = z
  .object({
    variant_id: z.string(),
    store_id: z.string(),
    in_stock: z.number(),
    updated_at: z.iso.datetime(),
  })
  .passthrough();

export const LvStoresResponseSchema = z.object({ stores: z.array(LvStoreSchema) }).passthrough();

export const LvItemsResponseSchema = z
  .object({
    items: z.array(LvItemSchema),
    cursor: z.string().nullable().optional(),
  })
  .passthrough();

export const LvReceiptsResponseSchema = z
  .object({
    receipts: z.array(LvReceiptSchema),
    cursor: z.string().nullable().optional(),
  })
  .passthrough();

export const LvInventoryResponseSchema = z
  .object({
    inventory_levels: z.array(LvInventoryLevelSchema),
    cursor: z.string().nullable().optional(),
  })
  .passthrough();
