/**
 * zod schemas for Loyverse REST API responses — external input is parsed at the boundary
 * (CLAUDE.md convention). Real API responses may carry fields not defined here, so
 * `.passthrough()` allows unknown fields while only the fields we actually use are validated
 * strictly. Shared by FixtureLoyverseClient (mocks) and the T3 real adapter (adapters/loyverseClient).
 */
import { z } from "zod";
import type { LvInventoryLevel, LvItem, LvReceipt, LvStore } from "../core/types.js";

export const LvStoreSchema = z
  .object({
    id: z.string(),
    name: z.string(),
  })
  .passthrough();

export const LvItemVariantSchema = z
  .object({
    variant_id: z.string(),
    sku: z.string().nullable(),
  })
  .passthrough();

export const LvItemSchema = z
  .object({
    id: z.string(),
    item_name: z.string(),
    category_id: z.string().nullable(),
    variants: z.array(LvItemVariantSchema).min(1),
  })
  .passthrough();

export const LvReceiptLineItemSchema = z
  .object({
    variant_id: z.string(),
    item_id: z.string(),
    quantity: z.number(),
    gross_total_money: z.number(),
    total_discount: z.number(),
  })
  .passthrough();

export const LvReceiptSchema = z
  .object({
    receipt_number: z.string(),
    store_id: z.string(),
    // "SALE" | "REFUND" — real API values. This field is required to distinguish refunds (the sign is flipped in the ETL).
    receipt_type: z.enum(["SALE", "REFUND"]),
    // Holds the original sale receipt number only on refund receipts. Official docs: "Only for refund receipts".
    refund_for: z.string().nullable(),
    // Auto-generated timestamp. Official docs: "The autogenerated date and time when the receipt was created".
    created_at: z.iso.datetime(),
    // Official docs: "The date and time when the receipt was updated." — the basis of the incremental sync watermark.
    updated_at: z.iso.datetime(),
    // Defaults to created_at but can be backdated to an earlier time (migrated data, etc.).
    receipt_date: z.iso.datetime(),
    // Cancellation time of a cancelled receipt. null if not cancelled.
    cancelled_at: z.iso.datetime().nullable(),
    line_items: z.array(LvReceiptLineItemSchema),
  })
  .passthrough();

export const LvInventoryLevelSchema = z
  .object({
    variant_id: z.string(),
    store_id: z.string(),
    in_stock: z.number(),
    updated_at: z.iso.datetime(),
  })
  .passthrough();

export const LvStoresResponseSchema = z.object({ stores: z.array(LvStoreSchema) }).passthrough();

export const LvItemsResponseSchema = z
  .object({
    items: z.array(LvItemSchema),
    cursor: z.string().nullable().optional(),
  })
  .passthrough();

export const LvReceiptsResponseSchema = z
  .object({
    receipts: z.array(LvReceiptSchema),
    cursor: z.string().nullable().optional(),
  })
  .passthrough();

export const LvInventoryResponseSchema = z
  .object({
    inventory_levels: z.array(LvInventoryLevelSchema),
    cursor: z.string().nullable().optional(),
  })
  .passthrough();

// ── Mappers: zod-validated raw response → internal Lv* types ─────────────────
// Shared by FixtureLoyverseClient (mocks) and the real adapter (loyverseClient) — after
// parsing, only the fields we actually use are narrowed and passed to the lower layers.

export function toLvStore(raw: z.infer<typeof LvStoreSchema>): LvStore {
  return { id: raw.id, name: raw.name };
}

export function toLvItem(raw: z.infer<typeof LvItemSchema>): LvItem {
  return {
    id: raw.id,
    item_name: raw.item_name,
    category_id: raw.category_id,
    variants: raw.variants.map((v) => ({ variant_id: v.variant_id, sku: v.sku })),
  };
}

export function toLvReceipt(raw: z.infer<typeof LvReceiptSchema>): LvReceipt {
  return {
    receipt_number: raw.receipt_number,
    store_id: raw.store_id,
    receipt_type: raw.receipt_type,
    refund_for: raw.refund_for,
    created_at: raw.created_at,
    updated_at: raw.updated_at,
    receipt_date: raw.receipt_date,
    cancelled_at: raw.cancelled_at,
    line_items: raw.line_items.map((li) => ({
      variant_id: li.variant_id,
      item_id: li.item_id,
      quantity: li.quantity,
      gross_total_money: li.gross_total_money,
      total_discount: li.total_discount,
    })),
  };
}

export function toLvInventoryLevel(raw: z.infer<typeof LvInventoryLevelSchema>): LvInventoryLevel {
  return {
    variant_id: raw.variant_id,
    store_id: raw.store_id,
    in_stock: raw.in_stock,
    updated_at: raw.updated_at,
  };
}
